### ISSUE TITLE
git 2.32 adds support for better format option

### ISSUE THREAD

**Issue by eli-schwartz** [Changaco/setuptools_scm_git_archive#17]
From the README:

> Note that it only works for archives of tagged commits (because git currently lacks a format option equivalent to `git describe --tags`).

I opened a discussion on the git mailing list back in January: https://public-inbox.org/git/4f65f02c-1d16-aa2c-3e7b-28d807b9ebe9@archlinux.org/T/

As a result, the git 2.32 release notes from 17 hours ago, mention this:
 * "git log --format='...'" learned "%(describe)" placeholder.

Full documentation on the format:
https://git-scm.com/docs/git-log/2.32.0#Documentation/git-log.txt-emdescribeoptionsem

setuptools_scm_git_archive should learn to read, in addition to:

```
ref-names: $Format:%D$
```

e.g.

```
describe-name: $Format:%(describe:match=v[0-9]*,exclude=*rc*)$
```

**Comment by Changaco** [comment]
If Git finally provides all the needed information, then support for Git archives should be added [upstream](https://github.com/pypa/setuptools_scm/) and this plugin should be deprecated.

Quote from the upstream README:

> The only reason for not including it in `setuptools_scm` itself is Git/GitHub not supporting sufficient metadata for untagged/followup commits, which is preventing a consistent UX.

**Comment by eli-schwartz** [comment]
Fair enough! Even better.

Opened https://github.com/pypa/setuptools_scm/issues/578
