### ISSUE TITLE
Local builds fail when setuptools_scm_git_archive enabled

### ISSUE THREAD

**Issue by jaraco** [Changaco/setuptools_scm_git_archive#2]
Consider the project at https://github.com/yougov/pycrunch/tree/scm-versioning

It fails to build in travis:

https://travis-ci.org/Crunch-io/pycrunch/jobs/113766604

You would expect non-tagged commits like that branch to have some fallback mechanism to assign a version rather than to outright fail.

Is there a solution for this condition, or is it necessarily the case that use of setuptools_scm_git_archive requires that setup.py can only be invoked against tagged commits or tarballs?

**Comment by Changaco** [comment]
The failure isn't coming from the plugin, so it looks to me like the problem is in `setuptools_scm`. I suggest trying https://github.com/pypa/setuptools_scm#environment-variables or switching to https://github.com/Changaco/version.py.

**Comment by jaraco** [comment]
Indeed. Turns out it was my mistake not upgrading setuptools and the issue was with setuptools_scm. Thanks for the kind response and suggestions.

**Comment by Changaco** [comment]
:-)

**Comment by anthrotype** [comment]
I had a similar issue when using `setuptools_scm_git_archive` on Appveyor, which I also fixed by upgrading setuptools.

The strange thing was that it was only failing on Python 3.4.4 (both 32 and 64 bit), but not on 2.7.12 or 3.5.2:
https://ci.appveyor.com/project/behdad/fonttools/build/1.0.498

After updating setuptools to the current version 25.2.0, the issue was fixed. Pip says the uninstalled version of setuptools was 18.2:
https://ci.appveyor.com/project/behdad/fonttools/build/job/7fck55a2dor2e0ua

It would be good to know the minimum version of setuptools that is required to successfully run setuptools_scm_git_archive.
Thanks.

**Comment by anthrotype** [comment]
I believe this is an issue with setuptools_scm_git_archive, or at least with the way old versions of setuptools interact with the combo setuptools_scm/setuptools_scm_git_archive -- though I'm still not sure which is the baseline setuptools that works.

So, if I tell pip to install setuptools==18.2 in a virtualenv on my local OSX machine, it fails in the same way as in the appveyor log above, when setuptools_scm_git_archive is enabled alongside setuptools_scm. 

Updating setuptools to the current version fixes it.

Also, removing support for setuptools_scm_git_archive, and using only setuptools_scm works with the older version of setuptools (only tried 18.2).

It appears that when using some older version of setuptools, and _both_ the *scm and *scm_git_archive are activated, the entry point of the latter always gets the precedence, even if not inside from a git archive.

This is with old setuptools 18.2, setuptools_scm 1.11.1 and setuptools_scm_git_archive 1.0

```
$ SETUPTOOLS_SCM_DEBUG=1 python setup.py sdist
root '/Users/cosimolupo/Documents/Github/fonttools'
looking for ep setuptools_scm.parse_scm /Users/cosimolupo/Documents/Github/fonttools
found ep .git_archival.txt = setuptools_scm_git_archive:parse
content 'ref-names: $Format:%D$\n'
data {'ref-names': '$Format:%D$'}
data {'ref-names': '$Format:%D$'}
Traceback (most recent call last):
  File "setup.py", line 73, in <module>
    **classifiers
  File "/usr/local/var/pyenv/versions/3.5.2/lib/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/var/pyenv/versions/fonttools352/lib/python3.5/site-packages/setuptools/dist.py", line 272, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/local/var/pyenv/versions/3.5.2/lib/python3.5/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/usr/local/var/pyenv/versions/fonttools352/lib/python3.5/site-packages/setuptools/dist.py", line 327, in finalize_options
    ep.load()(self, ep.name, value)
  File "/Users/cosimolupo/Documents/Github/fonttools/.eggs/setuptools_scm-1.11.1-py3.5.egg/setuptools_scm/integration.py", line 19, in version_keyword
  File "/Users/cosimolupo/Documents/Github/fonttools/.eggs/setuptools_scm-1.11.1-py3.5.egg/setuptools_scm/__init__.py", line 104, in get_version
  File "/Users/cosimolupo/Documents/Github/fonttools/.eggs/setuptools_scm-1.11.1-py3.5.egg/setuptools_scm/__init__.py", line 82, in _do_parse
LookupError: setuptools-scm was unable to detect version for '/Users/cosimolupo/Documents/Github/fonttools'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj  
```

This is with old setuptools 18.2 but without setuptools_scm_git_archive:

```
$ SETUPTOOLS_SCM_DEBUG=1 python setup.py sdist
root '/Users/cosimolupo/Documents/Github/fonttools'
looking for ep setuptools_scm.parse_scm /Users/cosimolupo/Documents/Github/fonttools
found ep .git = setuptools_scm.git:parse
cmd 'git rev-parse --show-toplevel'
out b'/Users/cosimolupo/Documents/Github/fonttools\n'
real root /Users/cosimolupo/Documents/Github/fonttools
cmd 'git rev-parse --verify --quiet HEAD'
out b'fc1187f7306728716e76aee51b09d80557d2a3b0\n'
cmd 'git describe --dirty --tags --long --match *.*'
out b'3.0-976-gfc1187f\n'
tag 3.0
version <Version('3.0')>
version 3.0
scm version <ScmVersion 3.0 d=976 n=gfc1187f d=False x={}>
config {'local_scheme': 'node-and-date', 'version_scheme': 'guess-next-dev'}
ep ('setuptools_scm.version_scheme', 'guess-next-dev')
ep ('setuptools_scm.local_scheme', 'node-and-date')
version 3.1.dev976
local_version +ngfc1187f
running sdist
[...]
```

This is with current setuptools 26.0.0 (but it was working with >=25.0 as well), and with both *scm and *scm_git_archive:

```
$ SETUPTOOLS_SCM_DEBUG=1 python setup.py sdist
root '/Users/cosimolupo/Documents/Github/fonttools'
looking for ep setuptools_scm.parse_scm /Users/cosimolupo/Documents/Github/fonttools
found ep .git = setuptools_scm.git:parse
cmd 'git rev-parse --show-toplevel'
out b'/Users/cosimolupo/Documents/Github/fonttools\n'
real root /Users/cosimolupo/Documents/Github/fonttools
cmd 'git rev-parse --verify --quiet HEAD'
out b'7cbd553a18273e1db38da287310ff2e162d434d8\n'
cmd 'git describe --dirty --tags --long --match *.*'
out b'3.0-977-g7cbd553\n'
tag 3.0
version <Version('3.0')>
version 3.0
scm version <ScmVersion 3.0 d=977 n=g7cbd553 d=False x={}>
config {'local_scheme': 'node-and-date', 'version_scheme': 'guess-next-dev'}
ep ('setuptools_scm.version_scheme', 'guess-next-dev')
ep ('setuptools_scm.local_scheme', 'node-and-date')
version 3.1.dev977
local_version +ng7cbd553
running sdist
[...]
```

/cc @jaraco @RonnyPfannschmidt @Changaco

**Comment by Changaco** [comment]
@anthrotype Thanks for tracking down the problem, but I don't see what change I could make to the plugin that would fix this.
