### ISSUE TITLE
Compatibility with the latest setuptools_scm

### ISSUE THREAD

**Issue by frenzymadness** [Changaco/setuptools_scm_git_archive#23]
This import no longer works:

https://github.com/Changaco/setuptools_scm_git_archive/blob/cfdcdc68f75621c5808726c15daff9e490ed6d07/tests.py#L2

It seems that `format_version` has to be imported from `setuptools_scm.version`.

**Comment by frenzymadness** [comment]
And it also seems that `setuptools_scm.utils` is not available anymore.

https://github.com/Changaco/setuptools_scm_git_archive/blob/cfdcdc68f75621c5808726c15daff9e490ed6d07/setuptools_scm_git_archive/__init__.py#L6

**Comment by Changaco** [comment]
This plugin isn't meant to be compatible with the latest versions `setuptools_scm`, because it is no longer needed nor useful since `setuptools_scm` 7.0.0 added built-in support for git archives.

**Comment by frenzymadness** [comment]
Interesting, thank you. Is there a migration guide somewhere?

**Comment by Changaco** [comment]
Yes, in the README.
